{
  "kind": "List",
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "PersistentVolume",
      "metadata": {
        "name": "sonarqube-data",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "capacity": {
            "storage": "10Gi"
          },
        "accessModes": [ "ReadWriteOnce" ],
        "hostPath": {
          "path": "/opt/sonarqube/data"
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolume",
      "metadata": {
        "name": "sonarqube-logs",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "capacity": {
            "storage": "10Gi"
          },
        "accessModes": [ "ReadWriteOnce" ],
        "hostPath": {
          "path": "/opt/sonarqube/logs"
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolume",
      "metadata": {
        "name": "sonarqube-extensions",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "capacity": {
            "storage": "10Gi"
          },
        "accessModes": [ "ReadWriteOnce" ],
        "hostPath": {
          "path": "/opt/sonarqube/extensions"
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolume",
      "metadata": {
        "name": "sonarqube-temp",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "capacity": {
            "storage": "10Gi"
          },
        "accessModes": [ "ReadWriteOnce" ],
        "hostPath": {
          "path": "/opt/sonarqube/temp"
        }
      }
    }
  ]
}
