
# Server Properties
server:
  port: 5000

# Spring Properties
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://bookstoredbinstance.ccvf1zgq4izw.us-east-2.rds.amazonaws.com:3306/bookstore
    username: root
    password: bcmc1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: prod
