
# Server Properties
server:
  port: 8080

# Spring Properties
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

  datasource:
    url: jdbc:postgresql://postgresdb:5432/mockdb
    username: admin
    password: Gosox07!
    driver-class-name: org.postgresql.Driver

logging:
  config: file:/opt/configuration/logback.xml

