# Server Properties
server:
  port: 8080


# Spring Properties
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: bcmc1234

  h2:
    console:
      enabled: true
      path: /h2-console
