
# Server Properties
server:
  port: 8080

# Spring Properties
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://mysql/bookstore?serverTimezone=UTC
    username: root
    password: bcmc1234
    driverClassName: com.mysql.cj.jdbc.Driver

