kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-temp
  annotations:
    #pv.beta.kubernetes.io/gid: "1234"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/sonarqube/temp"
