kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-postgresql
  annotations:
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1234"  
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/data/userdata"
