kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-extensions
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/sonarqube/extensions/"
