{
  "kind": "List",
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "sonarqube-data",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "storageClassName": "manual",
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
          "requests": {
            "storage": "10Gi"
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "sonarqube-logs",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "storageClassName": "manual",
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
          "requests": {
            "storage": "10Gi"
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "sonarqube-temp",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "storageClassName": "manual",
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
          "requests": {
            "storage": "10Gi"
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "sonarqube-extensions",
        "labels": {
          "name": "sonarqube"
        }
      },
      "spec": {
        "storageClassName": "manual",
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
          "requests": {
            "storage": "10Gi"
          }
        }
      }
    }
  ]
}
