kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: cicd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
