kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-data
  annotations:
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/jenkins/data"
