kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-data
  annotations:
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/data/userdata"
